//
// Created by tomly on 07/10/2026.
//

#ifndef F401_RE_HAL_STM32F401RE_HANDLERS_H
#define F401_RE_HAL_STM32F401RE_HANDLERS_H

#define WEAK_HANDLER(handler) void handler(void) __attribute__((weak, alias("Default_Handler")))

WEAK_HANDLER(NMI_Handler);
WEAK_HANDLER(HardFault_Handler);
WEAK_HANDLER(MMFault_Handler);
WEAK_HANDLER(BusFault_Handler);
WEAK_HANDLER(UsageFault_Handler);
WEAK_HANDLER(SVCall_Handler);
WEAK_HANDLER(DebugMon_Handler);
WEAK_HANDLER(PendSV_Handler);
WEAK_HANDLER(SysTick_Handler);
WEAK_HANDLER(WindowWatchdog_Handler);
WEAK_HANDLER(EXTI16_Handler);
WEAK_HANDLER(EXTI21_Handler);
WEAK_HANDLER(EXTI22_Handler);
WEAK_HANDLER(Flash_Handler);
WEAK_HANDLER(RCC_Handler);
WEAK_HANDLER(EXTI0_Handler);
WEAK_HANDLER(EXTI1_Handler);
WEAK_HANDLER(EXTI2_Handler);
WEAK_HANDLER(EXTI3_Handler);
WEAK_HANDLER(EXTI4_Handler);
WEAK_HANDLER(DMA1_Stream0_Handler);
WEAK_HANDLER(DMA1_Stream1_Handler);
WEAK_HANDLER(DMA1_Stream2_Handler);
WEAK_HANDLER(DMA1_Stream3_Handler);
WEAK_HANDLER(DMA1_Stream4_Handler);
WEAK_HANDLER(DMA1_Stream5_Handler);
WEAK_HANDLER(DMA1_Stream6_Handler);
WEAK_HANDLER(ADC_Handler);
WEAK_HANDLER(EXTI9_5_Handler);
WEAK_HANDLER(TIM1_BRK_TIM9_Handler);
WEAK_HANDLER(TIM1_UP_TIM10_Handler);
WEAK_HANDLER(TIM1_TRG_COM_TIM11_Handler);
WEAK_HANDLER(TIM1_CC_Handler);
WEAK_HANDLER(TIM2_Handler);
WEAK_HANDLER(TIM3_Handler);
WEAK_HANDLER(TIM4_Handler);
WEAK_HANDLER(I2C1_EV_Handler);
WEAK_HANDLER(I2C1_ER_Handler);
WEAK_HANDLER(I2C2_EV_Handler);
WEAK_HANDLER(I2C2_ER_Handler);
WEAK_HANDLER(SPI1_Handler);
WEAK_HANDLER(SPI2_Handler);
WEAK_HANDLER(USART1_Handler);
WEAK_HANDLER(USART2_Handler);
WEAK_HANDLER(EXTI15_10_Handler);
WEAK_HANDLER(EXTI17_Handler);
WEAK_HANDLER(EXTI18_Handler);
WEAK_HANDLER(DMA1_Stream7_Handler);
WEAK_HANDLER(SDIO_Handler);
WEAK_HANDLER(TIM5_Handler);
WEAK_HANDLER(SPI3_Handler);
WEAK_HANDLER(DMA2_Stream0_Handler);
WEAK_HANDLER(DMA2_Stream1_Handler);
WEAK_HANDLER(DMA2_Stream2_Handler);
WEAK_HANDLER(DMA2_Stream3_Handler);
WEAK_HANDLER(DMA2_Stream4_Handler);
WEAK_HANDLER(OTG_FS_Handler);
WEAK_HANDLER(DMA2_Stream5_Handler);
WEAK_HANDLER(DMA2_Stream6_Handler);
WEAK_HANDLER(DMA2_Stream7_Handler);
WEAK_HANDLER(USART6_Handler);
WEAK_HANDLER(I2C3_EV_Handler);
WEAK_HANDLER(I2C3_ER_Handler);
WEAK_HANDLER(FPU_Handler);
WEAK_HANDLER(SPI4_Handler);

#endif // F401_RE_HAL_STM32F401RE_HANDLERS_H
